### ISSUE TITLE
include grid_mapping in landsat_importer output

### ISSUE THREAD

**Issue by niallmcc** [surftemp/landsat_importer#2]
https://github.com/surftemp/gbcs/issues/1246#issuecomment-2270752512

From @oembury 

> Adding the auxiliary data (dem, land/sea mask etc) to the Level 1c in the gbcs pre-processor step would require the Level 1c to store the full projection information (i.e. retain the grid_mapping variable) so that we can ensure that the correct data is used. The current landsat L1c does not record the grid_mapping so we can not tell if a l1c input is on the CHUK grid, greenland, or some other projection.
> 
> This may require updates to landsat_importer (to record original landsat UTM grid); eo-pipelines?; and the regridding tool

We should also add this to the output from the regridding tool(s)

**Comment by oembury** [comment]
See #1 for my attempt to address this for landsat_importer

**Comment by niallmcc** [comment]
Ah OK, I will check the output from some test runs and close this issue if everything looks OK
